apiVersion: v1
entries:
  drupal-application:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-27T11:31:53.018327+05:30"
    description: A Helm chart for Kubernetes
    digest: e9493d63af3599d0f4d635a370c2b521e2a5521ffb68e38322a671e9382f6781
    name: drupal-application
    urls:
    - https://akashkaveti.github.io/drupal-helm-chart/charts/drupal-application-1.0.1.tgz
    version: 1.0.1
generated: "2020-04-27T11:31:53.017481+05:30"
