apiVersion: v1
entries:
  drupal-application:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-05-13T18:01:18.649195+05:30"
    description: A Helm chart for Kubernetes
    digest: a19cee352837f400bc47fd2b4fec83339772fe95d27f64fa3ef1df1e5c50bc7b
    name: drupal-application
    urls:
    - https://akashkaveti.github.io/drupal-helm-chart/charts/drupal-application-1.1.1.tgz
    version: 1.1.1
generated: "2020-05-13T18:01:18.646885+05:30"
