apiVersion: v1
entries:
  drupal-application:
  - apiVersion: v1
    appVersion: "1.0"
    created: "2020-04-20T15:00:17.297992+05:30"
    description: A Helm chart for Kubernetes
    digest: 415bcdad72d6066606bc250db84da0d7dda49edf19ca9e726de55d896d13e46a
    name: drupal-application
    urls:
    - https://akashkaveti.github.io/drupal-helm-chart/charts/drupal-application-0.1.7.tgz
    version: 0.1.7
generated: "2020-04-20T15:00:17.296731+05:30"
