apiVersion: apps/v1
kind: Deployment
metadata:
{{ if .Values.project.branch }}
  name: {{ .Values.project.name }}-{{ .Values.project.branch }}
{{ end }}
  name: {{ .Values.project.name }}
  labels:
{{ if .Values.project.branch }}
    app: {{ .Values.project.name }}-{{ .Values.project.branch }}
{{ end }}
    app: {{ .Values.project.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
{{ if .Values.project.branch }}
      app: {{ .Values.project.name }}-{{ .Values.project.branch }}
{{ end }}
      app: {{ .Values.project.name }}
  template:
    metadata:
      labels:
{{ if .Values.project.branch }}
        app: {{ .Values.project.name }}-{{ .Values.project.branch }}
{{ end }}
        app: {{ .Values.project.name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.project.image.pullSecret }}
      volumes:
        # Create the shared files volume to be used in both pods
        - name: app
          emptyDir: {}
        - name: drupal-files
          persistentVolumeClaim:
          {{ if .Values.project.branch }}
            claimName: {{ .Values.project.name }}-{{ .Values.project.branch }}-pvc
          {{ end }}
            claimName: {{ .Values.project.name }}-pvc
      containers:
      - name: php-fpm
        image: {{ .Values.project.image.registry }}/{{ .Values.project.image.repository }}:{{ .Values.project.image.tag }}
        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: {{ .Values.mariadb.rootUser.password }}
        - name: TRUSTED_HOST
          value: {{ .Values.project.ingress.host }}
        - name: K8S_ENABLED
          value: "true"
        - name: MYSQL_DB_HOST
          value: {{ .Release.Name }}-{{ .Values.mariadb.db.host }}
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: {{ .Values.mariadb.db.name }}
        - name: BEHAT_BASE_URL
          value: {{ .Values.project.ingress.host }}
        - name: SELENIUM_SERVICE
          value: {{ .Values.project.behat.selenium }}
        volumeMounts:
          - name: app
            mountPath: /app
          - name: drupal-files
            mountPath: /shared
        lifecycle:
          postStart:
            exec:
              command:
                - "/bin/sh"
                - "-c"
                - > 
                  cp -fr /code/. /app;
                  /app/post-deploy.sh
                  # rm -rf /app/web/sites/default/files;
                  # ln -s /shared /app/web/sites/default/files;
      - name: nginx
        image: {{ .Values.project.image.registry }}/{{ .Values.project.nginxImage.repository }}:{{ .Values.project.nginxImage.tag }}
        ports:
          - name: http
            containerPort: 8080
        volumeMounts:
          - name: app
            mountPath: /app
---
apiVersion: v1
kind: Service
metadata:
{{ if .Values.project.branch }}
  name: {{ .Values.project.name }}-{{ .Values.project.branch }}
{{ end }}
  name: {{ .Values.project.name }}
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
  selector:
{{ if .Values.project.branch }}
      app: {{ .Values.project.name }}-{{ .Values.project.branch }}
{{ end }}
      app: {{ .Values.project.name }}