{{- if .Values.project.persistence.enabled }}

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
{{ if .Values.project.branch }}
  name: {{ .Values.project.name }}-{{ .Values.project.branch }}-pvc
{{ end }}
  name: {{ .Values.project.name }}-pvc
  labels:
{{ if .Values.project.branch }}
    app: {{ .Values.project.name }}-{{ .Values.project.branch }}
{{ end }}
    app: {{ .Values.project.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.project.persistence.size | default "10G" | quote }}

{{- end }}