drupalVersion: v8
project:
  name: staples
  ingress:
    enabled: false
    host: localhost
  image:
    registry: registry.axl8.xyz
    repository: infra/staples
    tag: 497ed363
    pullSecret: docker-login
  nginxImage:
    registry: registry.axl8.xyz
    repository: infra/nginx
    tag: 651e31a0
    docroot: web
  persistence:
    enabled: true
  behat:
    selenium: http://selenium-chrome-service:9515
mariadb:
  rootUser:
    password: password
  db:
    host: mariadb
    name: drupal
    user: drupal
    password: password
dbDump:
  namespace: default
  minioBucket: webinars-db-dump
  minioObject: webinars.sql
  PullSecret: docker-mysql-client

