project:
  name: webinars
  ingress:
    enabled: false
    host: localhost
  image:
    registry: registry.axl8.xyz
    repository: infra/webinars
    tag: behat
    PullSecret: docker-infra-webinars
  persistence:
    enabled: false
  behat:
    selenium: http://selenium-chrome-service:9515
mariadb:
  rootUser:
    password: password
  db:
    host: mariadb
    name: drupal
    user: drupal
    password: password
dbDump:
  namespace: default
  minioBucket: webinars-db-dump
  minioObject: webinars.sql
  PullSecrets: docker-mysql-client

